spring:
  profiles:
    active: prod

info:
  component: Zuul Server

server:
  port: 8765
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

zuul:
  routes:
    foo-service:
      path: /foo/**
      service-id: foo-service
    bar-service:
      path: /bar/**
      service-id: bar-service